### ISSUE TITLE
Can't install ICS-VSBIO and extract Data Bytes

### ISSUE THREAD

**Issue by sppan** [intrepidcs/ICS_VSBIO#6]
![image](https://user-images.githubusercontent.com/38788112/236177892-4581bf7e-8012-4248-825c-dbd44f218e56.png)
![image](https://user-images.githubusercontent.com/38788112/236177999-084c144f-246d-4a18-838c-30b9f56300b3.png)
Not really sure what is the issue, can anyone help out?

**Comment by sppan** [comment]
The issue is resolved. I had installed MSVC 2023 and used msg.get_byte_from_data() to extract Data Bytes.
`from ICS_VSBIO import VSBReader as Reader

def extract_data(message):
    data_bytes = []
    for i in range(8):
        data_bytes.append(message.get_byte_from_data(i))
    data_bytes = data_bytes[::-1]
    data_binary = ''.join([bin(byte)[2:].zfill(8) for byte in data_bytes])
    return data_binary

out = []
log = Reader.VSBReader("test-vsb-file.vsb")
for msg in log:
    msg_id = '0x{:03X}'.format(msg.info.ArbIDOrHeader)
    if msg_id == '0x12D':
        data = extract_data(msg)
        curr = int(data[-32:-16], 2) * 0.1 - 600
        out.append(curr)
`

**Comment by CANhaozhe** [comment]
Hi,

May I ask a question.

How to get message timestamp?

Thanks in advance,

Haozhe

 

发件人: ***@***.*** ***@***.***> 代表 sppan
发送时间: 2023年5月9日 2:09
收件人: intrepidcs/ICS_VSBIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [intrepidcs/ICS_VSBIO] Can't install ICS-VSBIO and extract Data Bytes (Issue #6)

 

The issue is resolved. I had installed MSVC 2023 and used msg.get_byte_from_data() to extract Data Bytes.
`from ICS_VSBIO import VSBReader as Reader

def extract_data(message):
data_bytes = []
for i in range(8):
data_bytes.append(message.get_byte_from_data(i))
data_bytes = data_bytes[::-1]
data_binary = ''.join([bin(byte)[2:].zfill(8) for byte in data_bytes])
return data_binary

out = []
log = Reader.VSBReader("test-vsb-file.vsb")
for msg in log:
msg_id = '0x{:03X}'.format(msg.info.ArbIDOrHeader)
if msg_id == '0x12D':
data = extract_data(msg)
curr = int(data[-32:-16], 2) * 0.1 - 600
out.append(curr)
`
